name: CI/CD for React Todo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # ✅ better than 18

      - name: Install & Build
        run: |
          cd todo
          npm install
          npm run build

      - name: Check build folder
        run: ls -la todo/build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-file
          path: todo/build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-file
          path: todo/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # ✅ fix this
          publish_dir: ./todo/build
